export const COUPON_THEMES = [
  // ===== EXISTING 10 (cleaned) =====
  {
    id: "teal",
    name: "Teal Classic",
    primary: "#0f766e",
    footer: "#134e4a",
    text: "#ffffff",
  },
  {
    id: "midnight",
    name: "Midnight Black",
    primary: "#020617",
    footer: "#0f172a",
    text: "#ffffff",
  },
  {
    id: "royalBlue",
    name: "Royal Blue",
    primary: "#1e3a8a",
    footer: "#1e40af",
    text: "#ffffff",
  },
  {
    id: "sunset",
    name: "Sunset Orange",
    primary: "#ea580c",
    footer: "#9a3412",
    text: "#ffffff",
  },
  {
    id: "forest",
    name: "Forest Green",
    primary: "#14532d",
    footer: "#064e3b",
    text: "#ffffff",
  },
  {
    id: "plum",
    name: "Plum Purple",
    primary: "#581c87",
    footer: "#3b0764",
    text: "#ffffff",
  },
  {
    id: "rose",
    name: "Rose Red",
    primary: "#be123c",
    footer: "#881337",
    text: "#ffffff",
  },
  {
    id: "slate",
    name: "Slate Gray",
    primary: "#1f2933",
    footer: "#111827",
    text: "#ffffff",
  },
  {
    id: "gold",
    name: "Luxury Gold",
    primary: "#92400e",
    footer: "#78350f",
    text: "#fff7ed",
  },
  {
    id: "indigo",
    name: "Indigo Pro",
    primary: "#312e81",
    footer: "#1e1b4b",
    text: "#ffffff",
  },
  {
    id: "cleanWhite",
    name: "Clean White",
    primary: "#ffffff",
    footer: "#0f766e",
    text: "#0f172a",
  },
  {
    id: "ivoryGold",
    name: "Ivory Gold",
    primary: "#fffaf0",
    footer: "#92400e",
    text: "#3f2a1a",
  },
  {
    id: "cloudBlue",
    name: "Cloud Blue",
    primary: "#f8fafc",
    footer: "#2563eb",
    text: "#0f172a",
  },
  {
    id: "carbon",
    name: "Carbon Black",
    primary: "#09090b",
    footer: "#18181b",
    text: "#fafafa",
  },
  {
    id: "aquaPop",
    name: "Aqua Pop",
    primary: "#06b6d4",
    footer: "#0e7490",
    text: "#ffffff",
  },
];
