export const COUPON_THEMES = [
  {
    id: "teal",
    name: "Teal Classic",
    primary: "#0f766e",
    footer: "#134e4a",
    text: "#ffffff",
  },
  {
    id: "midnight",
    name: "Midnight Black",
    primary: "#020617",
    footer: "#0f172a",
    text: "#ffffff",
  },
  {
    id: "royalBlue",
    name: "Royal Blue",
    primary: "#1e3a8a",
    footer: "#1e40af",
    text: "#ffffff",
  },
  {
    id: "sunset",
    name: "Sunset Orange",
    primary: "#ea580c",
    footer: "#9a3412",
    text: "#ffffff",
  },
  {
    id: "forest",
    name: "Forest Green",
    primary: "#14532d",
    footer: "#064e3b",
    text: "#ffffff",
  },
  {
    id: "plum",
    name: "Plum Purple",
    primary: "#581c87",
    footer: "#3b0764",
    text: "#ffffff",
  },
  {
    id: "rose",
    name: "Rose Red",
    primary: "#be123c",
    footer: "#881337",
    text: "#ffffff",
  },
  {
    id: "slate",
    name: "Slate Gray",
    primary: "#1f2933",
    footer: "#111827",
    text: "#ffffff",
  },
  {
    id: "gold",
    name: "Luxury Gold",
    primary: "#92400e",
    footer: "#78350f",
    text: "#fff7ed",
  },
  {
    id: "indigo",
    name: "Indigo Pro",
    primary: "#312e81",
    footer: "#1e1b4b",
    text: "#ffffff",
  },
];
